# Generated by Django 5.2 on 2026-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
