# Generated by Django 5.2 on 2026-04-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_internshipplacement_student_and_more'),
        ('core', '0005_userprofile'),
    ]

    operations = [
    ]
