# Generated by Django 5.2 on 2026-05-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260429_2142'),
        ('core', '0006_merge_20260429_2301'),
    ]

    operations = [
    ]
