# Generated by Django 5.2 on 2026-05-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260502_0010'),
        ('core', '0007_merge_20260502_1208'),
    ]

    operations = [
    ]
