# Generated by Django 5.2 on 2026-05-04 20:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260504_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_items', to='core.evaluationcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='core.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'criteria')},
            },
        ),
    ]
