# Generated by Django 5.2 on 2026-05-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_evaluation_score_evaluation_communication_and_more'),
        ('core', '0010_alter_evaluation_options_and_more'),
    ]

    operations = [
    ]
