# Generated by Django 5.2 on 2026-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
