# Generated by Django 5.2 on 2026-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_old_evaluation_fields'),
        ('core', '0013_add_evaluation_week_number_and_score'),
    ]

    operations = [
    ]
