# Generated by Django 5.2 on 2026-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='week_number',
        ),
    ]
