# Generated by Django 5.2 on 2026-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('placement_created', 'Placement Created'), ('placement_status_updated', 'Placement Status Updated'), ('log_submitted', 'Log Submitted'), ('welcome', 'Welcome Message')], max_length=40),
        ),
    ]
